name: Deploy to AlwaysData

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-quaiantiquespaacetree.alwaysdata.net
          username: quaiantiquespaacetree
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          port: 21
          local-dir: ./  # Répertoire local
          server-dir: /www/  # Répertoire distant
          security: strict  # Forcer des connexions TLS sécurisées
          passive: false    # Test avec le mode actif si nécessaire
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          log-level: verbose


          
