name: Deploy to AlwaysData

# Déclenchement du workflow
on:
  push:
    branches:
      - main  # Exécute le workflow uniquement sur la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-quaiantiquespaacetree.alwaysdata.net
          username: quaiantiquespaacetree
          password: ${{ secrets.ftp_password }}
          protocol: ftp
          local-dir: # Exemple : dossier local à envoyer
          server-dir: /www/ # Chemin distant
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/bootstrap/scss/**
            **/node_modules/bootstrap/js/**
          log-level: standard

          
